//! Wrapper around the TSLanguage structure.

const api = @import("api/out.zig");
const symbol_api = @import("symbol.zig");

/// Language struct, equivalent of `TSLanguage` struct.
pub const Language = struct {
    language: *const api.TSLanguage,

    /// Get the version number for this language. This version number is used to ensure
    /// that language was generated by a compatible version of Tree-Sitter.
    fn version(self: Language) u32 {
        return api.ts_language_version(self.language);
    }

    /// Get the number of distinct node types in the language.
    fn symbol_count(self: Language) u32 {
        return api.ts_language_symbol_count(self.language);
    }

    /// Get a node type string for the given numerical id.
    fn symbol_name(self: Language, symbol: symbol_api.Symbol) []const u8 {
        return api.ts_language_symbol_name(self.language, symbol.symbol);
    }

    /// Get the numerical id for the given node type string.
    fn symbol_for_name(self: Language, str: []const u8, is_named: bool) symbol_api.Symbol {
        return symbol_api.Symbol.init(api.ts_language_symbol_for_name(self.language, str, str.len, is_named));
    }
};
